"""
Sphinx configuration for Zebra Sol Flasher.
Auto-generated by zebradocs_bootstrap.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent
REPO_ROOT = DOCS_DIR.parent

sys.path.insert(0, str(REPO_ROOT))

project = 'Zebra_SOL_Flasher'
author = ''
copyright = ""
release = os.environ.get("DOCS_VERSION", "dev")

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "autoapi.extension",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]

autosummary_generate = True
autodoc_member_order = "bysource"
autoclass_content = "both"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
autodoc_typehints = "description"

autodoc_mock_imports = [
    'bluetooth',
    'framebuf',
    'machine',
    'micropython',
    'network',
    'uasyncio',
    'ubinascii',
]

autoapi_type = "python"
autoapi_dirs = [
    '../robot',
]
autoapi_keep_files = True
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
    "imported-members",
]

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
]

html_title = f"{project} documentation"
